INSERT OR IGNORE INTO units (fullform, shortform) VALUES
    ('Kilogram', 'kg'),
    ('Gram', 'g'),
    ('Milligram', 'mg'),
    ('Tonne', 't'),
    ('Litre', 'L'),
    ('Millilitre', 'mL'),
    ('Piece', 'pc'),
    ('Dozen', 'doz'),
    ('Packet', 'pkt'),
    ('Bottle', 'btl'),
    ('Jar', 'jar'),
    ('Can', 'can'),
    ('Bag', 'bag'),
    ('Box', 'box'),
    ('Tray', 'tray'),
    ('Bunch', 'bunch'),
    ('Slice', 'slice'),
	('Head', 'head'),
	('Centimetre', 'cm'),
    ('Metre', 'm'),
    ('Square metre', 'm²'),
    ('Cubic metre', 'm³');