INSERT OR IGNORE INTO sub_categories (name, category_id) VALUES
    ('Chicken', 1),
    ('Fish & Seafood', 1),
    ('Eggs', 1),
    ('Pork', 1),
    ('Beef', 1),
    ('Milk', 2),
    ('Yoghurt', 2),
    ('Fresh Cheese', 2),
    ('Hard Cheese', 2),
    ('Sliced Cheese', 2),
    ('Milk Alternatives', 2),
    ('Rice', 3),
    ('Lentils', 3),
    ('Flour', 3),
    ('Pasta', 3),
    ('Cereals & Muesli', 3),
    ('Flatbreads & Wraps', 3),
    ('Whole Grains', 3),
    ('Ready-to-Eat', 4),
    ('Frozen Foods', 4),
    ('Frozen Vegetables & Fruits', 4),
    ('Convenience Foods', 4),
    ('Chips & Crisps', 5),
    ('Sweets & Chocolates', 5),
    ('Biscuits & Cookies', 5),
    ('Nuts & Seeds', 5),
    ('Fruits', 6),
    ('Vegetables', 6),
    ('Fresh Herbs', 6),
    ('Fresh Spices', 6),
    ('Water', 7),
    ('Juices & Smoothies', 7),
    ('Soft Drinks', 7),
    ('Coffee & Tea', 7),
    ('Alcohilic Beverages', 7),
    ('Bread', 8),
    ('Pastries & Cakes', 8),
    ('Buns & Rolls', 8),
    ('Cooking Sauces', 9),
    ('Dressings', 9),
    ('Vinegars', 9),
    ('Dried Herbs', 10),
    ('Dried Spices', 10),
    ('Ground Spices', 10),
    ('Salt & Pepper', 10),
    ('Cooking Oils', 11),
    ('Butter & Margarine', 11),
    ('Speciality Fats', 11),
    ('Household Items', 12),
    ('Personal Care & Hygiene', 12),
    ('Others', 12);